  Devop3:
                docker:
                         - image: circleci/python:3.10.4
     steps:
               - run:
                        name: Install Dependencies
                        command: timeout 1m lscpu
